include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    public_member_api_docs: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
